apiVersion : apps/v1
kind: Deployment
metadata:
  name: appnginxaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appnginxaks
  template:
    metadata:
      labels:
        app: appnginxaks 
    spec:
      containers:
        - name: appnginxaks 
          image: aksdevopsacr45.azurecr.io/appnginxaks
          ports:
          - containerPort: 80